spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/knowimage/GateWay.git
          search-paths: resources
          username: penglei@knowimage.cn
          password: Pl98629
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.107:10080/eureka
server:
  port: 8769
