spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shard
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.107:10080/eureka
server:
  port: 8769
