spring:
  datasource:
    url: jdbc:mysql://d1.knowimage.cn:10052/clinical_pathway?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: eladmin_user
    password: xyz@234
  redis:
    database: 1
    host: 192.168.50.244
    port: 6379
    password:
    timeout: 5000
  application:
    name: backendadmin
  mvc:
    static-path-pattern: /tableImage/**
  resources:
    static-locations: file:C://Users//wh123//Desktop//HospitalProject/TableImages


mybatis:
  type-aliases-package: cn.knowimage.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  address: 0.0.0.0
  max-http-header-size: 404857600
  jetty:
    max-http-post-size: 819200
  tomcat:
    max-http-get-size: 20971520
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@192.168.50.107:10080/eureka/
  instance:
    prefer-ip-address: true
    hostname: EurekaServer1
    instance-id: 192.168.50.5:backendadmin:9999
    ip-address: 192.168.50.5
