spring:
  application:
    name: BPMN-FRAMEWORK

  #链路追踪相关配置
    name: userService
  boot:
    admin:
      client:
        url: http://192.168.50.107:10001
#链路追踪相关配置
  zipkin:
    base-url: http://192.168.50.107:10002
    enabled: true
    sender:
      type: WEB
  #  采样率
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.107:10080/eureka

#打开feign的熔断机制
feign:
  hystrix:
    enabled: true

#请求连接的超时时间
ribbon:
  ConnectTimeOut: 4000
#请求处理的超时时间
  ReadTimeout: 4000
#  首次实例重试次数
  MaxAutoRetries: 1
#  其他实例重试次数
  MaxAutoRetriesNextServers: 0
#  是否开启所有实例的重试
  OkToRetryOnAllOperations: false

  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置hystrix的超时时长 这里尽量使该时长 大于ribbon的响应时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    shutdown:
      enabled: true
#    health:
#      show-details: ALWAYS  #显示详细信息



