spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eurekaServer
  boot:
    admin:
      client:
        url: http://192.168.50.107:10001
  cloud:
    client:
      ip-address: 192.168.50.184
  security:
    user:
      name: user
      password: 123456


eureka:
  instance:
    prefer-ip-address: true
    hostname: EurekaServer4
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    metadata-map:
      user.name: user
      user.password: 123456
  client:
    service-url:
      defaultZone: http://user:123456@192.168.50.154:10082/eureka,http://user:123456@192.168.50.107:10080/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    peer-node-read-timeout-ms: 1000



server:
  port: 10084


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
