spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eurekaServer
  boot:
    admin:
      client:
        url: http://192.168.50.107:10001
  cloud:
    client:
      ip-address: 192.168.50.184

eureka:
  instance:
    prefer-ip-address: true
    hostname: EurekaServer4
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://192.168.50.5:10080/eureka,http://192.168.50.154:10082/eureka
    register-with-eureka: true
    fetch-registry: true




server:
  port: 10084


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true