spring:
  application:
    name: gateway
  zipkin:
    base-url: http://192.168.50.107:10002
    enabled: true
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1
  cloud:
    client:
      ip-address: 192.168.50.154

server:
  port: 10005

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.107:10080/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
#路由相关配置 以key-value形式定义
zuul:
  routes:
    smsService: /smsService/**
    userService: /userService/**
    CLOUDPORTAL: /cloudportal/**
    BACKENDADMIN: /backendadmin/**

#请求连接的超时时间
ribbon:
  ConnectTimeOut: 3000
  #请求处理的超时时间
  ReadTimeout: 2000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000


management:
  endpoints:
    web:
      exposure:
        include: "*"
