spring:
  application:
    name: SmsService
  boot:
    admin:
      client:
        url: http://localhost:10001
  zipkin:
    base-url: http://localhost:10002
    enabled: true
    sender:
      type: WEB
  #  采样率
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka
