spring:
  application:
    name: admin-server
server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.184:10084/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
