spring:
  application:
    name: admin-server
  security:
    user:
      name: user
      password: 123456

server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@192.168.50.107:10080/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
