spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://192.168.50.236:10001
  zipkin:
    base-url: http://192.168.50.236:10002
    enabled: true
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1
#server:
#  port: 10000

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.236:10080/eureka

#路由相关配置 以key-value形式定义
zuul:
  routes:
    smsService: /smsService/**
    userService: /userService/**
    PCWIKI: /pcwiki/**
    ELADMIN: /eladmin/**

#请求连接的超时时间
ribbon:
  ConnectTimeOut: 3000
  #请求处理的超时时间
  ReadTimeout: 2000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000


management:
  endpoints:
    web:
      exposure:
        include: "*"
