spring:
  application:
    name: zipkinService
  main:
#    后定义的bean会覆盖之前的bean
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.236:10080/eureka

server:
  port: 10002

#  关闭自动配置启用所有请求得检测
management:
  metrics:
    web:
      server:
        auto-time-requests: false
